### ISSUE TITLE
Bounce too severe?

### ISSUE THREAD

**Issue by richarddas** [e-sites/ESArcProgressView#3]
When using `animateTo:withDuration:withEasingFunction:withUpdateHandler` with a duration of `1.f` and the `BounceEaseOut` easing function, the bounce is too severe - is there any way to adjust this?

**Comment by basvankuijck** [comment]
I'm using <a href="https://github.com/warrenm/AHEasing">AHEasing</a> for easing functions.
You could write your own `CustomBounceEaseOut` function by playing around with some values in https://github.com/warrenm/AHEasing/blob/master/AHEasing/easing.c

**Comment by richarddas** [comment]
Thanks for the prompt reply. In fact, `CircularEaseOut` seems to be the most appropriate for approximating WatchKit. Thanks!

**Comment by basvankuijck** [comment]
You're welcome!
